#ifndef SCREEN_MANAGER_H
#define SCREEN_MANAGER_H

typedef enum {
  MAIN_MENU,
  SETTINGS_MENU,
  CAMPAIGN_MENU,
  MULTIPLAYER_MENU,
  ADVANCEMENTS_MENU,
  GAME,
  FRIDGE_SCREEN,
  STOVE_SCREEN,
  OVEN_SCREEN,
  DEEP_FRY_SCREEN,
  GRILL_SCREEN,
  BARMINIGAME_SCREEN
} GameScreen;

#endif
